[app]
project_path = 'opt/sof_stats' # путь к проекту от корня /
self_api_port = 7006 # порт фаст апи
self_api_host = "127.0.0.1" # адрес фаст апи бэка
env_mode = "TEST" # окружение для запуска
stop_delay = 3 # задержка перед закрытием

[logger]
log_level = 'DEBUG' # уровень логирования. По умолчанию TRACE если env_mode TEST, иначе DEBUG
log_console = true # дублировать логи в консоль
console_lvl = 'TRACE'   # уровень логирования для консоли, если log_console True
rotation_size = "250 MB" # размер лога для начала ротации
retention_time = 5 # время в днях до начала ротации

[network]
max_requests = 1 # максимальное количество запросов к stackoverflow
max_alive_requests = 1  # максимальное количество активных (keep-alive) запросов к stackoverflow
keep_alive = 5 # время в секундах для keep-alive
timeout = 10  # тайм-аут в секундах для запросов к stackoverflow

[stackoverflow]
url = "https://api.stackexchange.com/2.3/search" # url-адрес для запросов к stackoverflow
pagesize = 100 # кол-во вопросов по тегу
order = "desc" # порядок
sort = "creation" # сортировка
site = "stackoverflow" # название внутреннего домена для поиска